# Generated by Django 2.2.4 on 2019-08-31 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('first_app', '0003_auto_20190831_0557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='TeamName',
        ),
    ]
