# Generated by Django 2.2.4 on 2019-08-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_entries_teamleader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='teamleader',
            field=models.CharField(default='Samyak', max_length=264),
        ),
    ]
