# Generated by Django 2.2.4 on 2019-08-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20190831_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='teamleader',
        ),
        migrations.AddField(
            model_name='entries',
            name='name',
            field=models.CharField(default='Samyak', max_length=100),
        ),
    ]
