# Generated by Django 2.2.4 on 2019-08-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20190831_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='name',
            field=models.CharField(default='Team Leader name Here', max_length=100),
        ),
    ]
