# Generated by Django 2.2.4 on 2019-08-31 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20190831_0628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entries',
            new_name='Entrie',
        ),
    ]
